/* ============================================================
   DAA Lab-05, Q4: Heap Sort of N randomly generated elements
                   stored in a file
   ============================================================
   Input representation: a text file "input.txt" containing N
   randomly generated integers (one per line), generated by this
   program. The array is read into memory, sorted via Heap Sort
   (using an implicit binary max-heap stored in the array itself
   -- no extra structure needed), and the sorted result is written
   to "output.txt".

   ---------------- Algorithm ----------------
   1. Build-Max-Heap: convert a[0..n-1] into a max-heap in place
      by calling sift-down (heapify) on every non-leaf node,
      from the last non-leaf node up to the root.
   2. Repeatedly swap the heap's root (the current maximum) with
      the last element of the heap, shrink the heap size by 1,
      and sift-down the new root to restore the heap property.
      After n-1 such extractions, the array is sorted ascending.

   ---------------- Complexity ----------------
   - Build-Max-Heap: although a single sift-down costs O(log n)
     in the worst case, summing the actual work over all nodes
     (most nodes are near the bottom of the tree and need very
     little sifting) gives a TIGHT bound of O(n), not O(n log n)
     (standard result: Sum_{h=0}^{log n} (n / 2^(h+1)) * h = O(n)).
   - Extract-max + sift-down, done n times: each sift-down costs
     O(log n), so this phase costs O(n log n).
   - Total worst-case (and best-case, and average-case) time:
     **O(n log n)** -- unlike Quicksort, Heap Sort has NO O(n^2)
     worst case, because the heap always stays balanced (implicit
     complete binary tree) regardless of input order.
   - Space: **O(1)** extra (sorts in place using the array itself
     as the heap; only O(log n) implicit recursion depth if
     sift-down is written recursively -- here it is written
     iteratively, so truly O(1) auxiliary space).
   - File I/O: reading/writing N integers adds O(n).
   ============================================================ */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void swap(int *a, int i, int j) { int t = a[i]; a[i] = a[j]; a[j] = t; }

/* sift-down (heapify) node i in a max-heap of the given size.
   Iterative version -> O(1) extra space; O(log n) worst-case time. */
void sift_down(int *a, int size, int i) {
    while (1) {
        int left = 2 * i + 1, right = 2 * i + 2, largest = i;
        if (left < size && a[left] > a[largest]) largest = left;
        if (right < size && a[right] > a[largest]) largest = right;
        if (largest == i) break;
        swap(a, i, largest);
        i = largest;
    }
}

/* Build-Max-Heap: O(n) (tight bound, not O(n log n)) */
void build_max_heap(int *a, int n) {
    for (int i = n / 2 - 1; i >= 0; i--)
        sift_down(a, n, i);
}

/* Heap Sort: O(n log n) worst/average/best case */
void heap_sort(int *a, int n) {
    build_max_heap(a, n);
    for (int end = n - 1; end > 0; end--) {
        swap(a, 0, end);       /* move current max to its final position */
        sift_down(a, end, 0);  /* restore heap property on the shrunk heap */
    }
}

/* ---------------- file helpers ---------------- */
void generate_input_file(const char *filename, int n, int max_val) {
    FILE *f = fopen(filename, "w");
    if (!f) { perror("fopen (write input)"); exit(1); }
    for (int i = 0; i < n; i++)
        fprintf(f, "%d\n", rand() % max_val);
    fclose(f);
}

int *read_ints_from_file(const char *filename, int *out_n) {
    FILE *f = fopen(filename, "r");
    if (!f) { perror("fopen (read)"); exit(1); }

    int capacity = 1024, n = 0;
    int *a = malloc(capacity * sizeof(int));
    int value;
    while (fscanf(f, "%d", &value) == 1) {
        if (n == capacity) { capacity *= 2; a = realloc(a, capacity * sizeof(int)); }
        a[n++] = value;
    }
    fclose(f);
    *out_n = n;
    return a;
}

void write_ints_to_file(const char *filename, int *a, int n) {
    FILE *f = fopen(filename, "w");
    if (!f) { perror("fopen (write output)"); exit(1); }
    for (int i = 0; i < n; i++) fprintf(f, "%d\n", a[i]);
    fclose(f);
}

int is_sorted(int *a, int n) {
    for (int i = 1; i < n; i++) if (a[i - 1] > a[i]) return 0;
    return 1;
}

int main(int argc, char **argv) {
    srand((unsigned) time(NULL));

    int N = 20;
    if (argc > 1) N = atoi(argv[1]);

    const char *infile = "input.txt";
    const char *outfile = "output.txt";

    printf("Generating %d random integers into '%s' ...\n", N, infile);
    generate_input_file(infile, N, 100000);

    int n;
    int *a = read_ints_from_file(infile, &n);
    printf("Read %d integers from '%s'.\n", n, infile);

    if (n <= 30) {
        printf("Before sort: [");
        for (int i = 0; i < n; i++) printf("%d%s", a[i], i == n - 1 ? "" : ", ");
        printf("]\n");
    }

    clock_t t0 = clock();
    heap_sort(a, n);
    clock_t t1 = clock();

    if (n <= 30) {
        printf("After sort:  [");
        for (int i = 0; i < n; i++) printf("%d%s", a[i], i == n - 1 ? "" : ", ");
        printf("]\n");
    }

    printf("Sorted correctly: %s\n", is_sorted(a, n) ? "yes" : "NO - BUG");
    printf("Heap Sort time for n=%d: %.6fs\n", n, (double)(t1 - t0) / CLOCKS_PER_SEC);

    write_ints_to_file(outfile, a, n);
    printf("Sorted output written to '%s'.\n", outfile);

    free(a);

    /* ---------------- empirical timing for larger n ---------------- */
    printf("\n--- Empirical timing (expect ~O(n log n), no O(n^2) worst case) ---\n");
    for (int size = 50000; size <= 400000; size *= 2) {
        generate_input_file("tmp_input.txt", size, 1000000000);
        int nn;
        int *arr = read_ints_from_file("tmp_input.txt", &nn);

        clock_t s0 = clock();
        heap_sort(arr, nn);
        clock_t s1 = clock();

        printf("n=%7d  heapsort time: %.6fs  sorted=%s\n",
               nn, (double)(s1 - s0) / CLOCKS_PER_SEC, is_sorted(arr, nn) ? "yes" : "NO-BUG");
        free(arr);
    }
    remove("tmp_input.txt");

    return 0;
}
